print("Hello World!")
print("Goodbye World!")
print("Testing Commit")
print("Another Try")
print("Python in VS Code")
print("Just installed PIP")
print("This is busting my balls")
print("Now I'm in Sublime")